VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VibExchange.Areas.RemoteAnalysis.Models;
using VibExchange.Filters;
using VibExchange.Areas.RemoteAnalysis;
using VibExchange.Models;
using System.Data;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Configuration;
using RestSharp;
using VibExchange.Areas.Helper;
using Newtonsoft.Json;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Collections;
using Microsoft.Reporting.WebForms;


namespace VibExchange.Areas.RemoteAnalysis.Controllers
{
    [InitializeSimpleMembershipAttribute]
    public class UploadController : Controller
    {
        string[] ChannelInput = { "Int 1", "Int 2", "Int 3", "Off" };
        string[] AmpMode = { "Lin A", "Int1 V", "Int2 S", "Env" };
        string[] WType = { "Rectangular", "Hanning" };
        string[] TrigMode = { "Free Run", "Internal", "External" };
        string[] AvgMode = { "Off", "Linear Frequency Domain", "Exponantial Frequency Domain", "Linear Time Domain", "Exponantial Time Domain" };
        int[] EnvelopingFrequency = { 2, 4, 8, 16, 32 };
        private string fileLocation = "~/Files/";
        [HttpGet]
        public ActionResult DataUpload(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult DataUpload(FormCollection formCollection, HttpPostedFileBase[] files, string ReturnUrl)
        {
            bool sts = ModelState.IsValid;
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Files["UploadedFile"];
                if (file == null)
                {
                    ModelState.AddModelError("FileName", "Please Upload Your file");
                }
                else if (file.ContentLength > 0)
                {
                    int MaxContentLength = 1024 * 1024 * 150; //150 MB
                    if (file.ContentLength > MaxContentLength)
                    {
                        ModelState.AddModelError("FileName", "Your file is too large, maximum allowed size is: " + MaxContentLength + " MB. Please zip your file and upload again.");
                    }
                    else
                    {
                        using (DBClass context = new DBClass())
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            string fname = Session["UserName"].ToString() + "@" + fileName;
                            var path = Path.Combine(Server.MapPath("~/Files"), fname);

                            if (System.IO.File.Exists(path))
                            {
                                ModelState.AddModelError("File", "This file already exist!");
                                ViewBag.errorsOccurred = "You have already upload this file before ! Please rename your file or upload another file.";
                                TempData["Error"] = "You have already upload this file before ! Please rename your file or upload another file.";
                                return View();
                            }
                            context.AddParameter("@UserID", Session["UserName"].ToString());
                            context.AddParameter("@FileName", fname);
                            context.AddParameter("@FileType", formCollection["btnRadio"]);
                            context.AddParameter("@InstrumentUsed", "Kohtect-C911");
                            context.AddParameter("@AnalysisMethod", "Remote Analysis");
                            context.AddParameter("@ImagePath", path);
                            context.AddParameter("@Description", formCollection["Description"]);
                            context.AddParameter("@id", null, SqlDbType.Int, ParameterDirection.Output);
                            int count = Convert.ToInt32(context.ExecuteNonQuery("addUploadDataRAM", CommandType.StoredProcedure, ParameterDirection.Output, "@id"));
                            if (count > 0)
                            {
                                file.SaveAs(path);
                                Session["CurrentFilePath"] = path;
                                Session["CurrentFileID"] = count;
                                TempData["FileID"] = count;
                                ViewBag.Message = "File uploaded successfully";
                                return RedirectToAction("GetAnalysisKohtect", "Kohtect", new { fileid = count });
                            }
                            else
                            {
                                ModelState.AddModelError("", "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.");
                            }
                        }
                    }
                }
            }
            return View();
        }

        public ActionResult GetAnalysisKohtect(FileDetail _file)
        {
            try
            { }
            catch { }
            return View();
        }

        [HttpPost]
        public ActionResult RouteDetail(string param)
        {
            try
            {
                PlantData plant = new PlantData();
                PointData point = new PointData();
                ArrayList lstffBearings = new ArrayList();
                int row;
                int a = getIndexofNumber(param);
                string NodeNumber = param.Substring(a, param.Length - a);
                row = Convert.ToInt32(NodeNumber);
                string NodeType = param.Substring(0, a);


                switch (NodeType)
                {
                    case "Plant":
                        {
                            using (DBClass context = new DBClass())
                            {
                                context.AddParameter("@Nodeid", param);
                                DataTable dtPlant = context.getData("GetPlantDetail", CommandType.StoredProcedure);
                                if (dtPlant.Rows.Count > 0)
                                {
                                    foreach (DataRow plantitem in dtPlant.Rows)
                                    {
                                        plant.PlantID = Convert.ToString(plantitem["NodeID"]);
                                        plant.PlantName = Convert.ToString(plantitem["PlantName"]);
                                        plant.PlantCategory = Convert.ToString(plantitem["Category"]);
                                        plant.PlantDetail = Convert.ToString(plantitem["PlantDetail"]);
                                    }
                                    ViewBag.NodeType = "Plant";
                                    Session["CurrentNodeID"] = plant.PlantID;
                                    return PartialView("_DisplayPlant", plant);
                                }
                                else
                                {
                                    TempData["NodeAvailability"] = "There is no any 'Plant' for display ! Please click on 'Add New Plant' button for create new 'Plant'.";
                                    return PartialView("_PlantDetail", plant);
                                }
                            }
                        }
                    case "Area":
                        {
                            using (DBClass context = new DBClass())
                            {
                                AreaData area = new AreaData();
                                context.AddParameter("@Nodeid", param);
                                DataTable dtArea = context.getData("GetAreaDetail", CommandType.StoredProcedure);
                                if (dtArea.Rows.Count > 0)
                                {
                                    foreach (DataRow areaItem in dtArea.Rows)
                                    {
                                        area.AreaID = Convert.ToString(areaItem["NodeID"]);
                                        area.AreaName = Convert.ToString(areaItem["AreaName"]);
                                        area.AreaDetail = Convert.ToString(areaItem["AreaDetail"]);
                                    }
                                    ViewBag.NodeType = "Area";
                                    Session["CurrentNodeID"] = area.AreaID;
                                    return PartialView("_DisplayArea", area);
                                }
                                else
                                {
                                    TempData["NodeAvailability"] = "There is no any 'Area' for display ! ";
                                    return PartialView("_DisplayArea", area);
                                }
                            }
                        }
                    case "Train":
                        {
                            using (DBClass context = new DBClass())
                            {
                                TrainData train = new TrainData();
                                context.AddParameter("@Nodeid", param);
                                DataTable dtTrain = context.getData("GetTrainDetail", CommandType.StoredProcedure);
                                if (dtTrain.Rows.Count > 0)
                                {
                                    foreach (DataRow trainItem in dtTrain.Rows)
                                    {
                                        train.TrainID = Convert.ToString(trainItem["NodeID"]);
                                        train.TrainName = Convert.ToString(trainItem["TrainName"]);
                                        train.TrainDetail = Convert.ToString(trainItem["TrainDetail"]);

VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Views/Upload/DataUpload.cshtml
@model VibExchange.Areas.RemoteAnalysis.Models.FileDetail
@{
    ViewBag.Title = "Upload Data";
    Layout = "~/Views/Shared/_VibExchangeLayout.cshtml";
}
<style>
    .full-height {
        height: 100%;
        background-color: transparent;
    }

    .form-height {
        margin-top: -80px;
    }

    .form-v-middle {
        margin-top: 12%;
    }
</style>
<div class="container full-height">
    <div class="row form-height">
        <div class="col-sm-6 col-sm-offset-3 well form-v-middle">
            <legend style="color: chocolate;">Please Upload Your Data. </legend>
            @using (Html.BeginForm("DataUpload", "Upload", new { ReturnUrl = this.Request.RawUrl }, FormMethod.Post, new { enctype = "multipart/form-data", @class = " form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group ">
                    @Html.RequiredLabelFor(model => model.InstrumentUsed, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownList("Instrument", new List<SelectListItem>{
                    new SelectListItem{ Text="IMPAQ-ELITE", Value = "IMPAQ-ELITE" },
                     new SelectListItem{ Text="DI-460", Value = "DI-460"},
                      new SelectListItem{ Text="ENPAC", Value = "NPAQ" },
                       new SelectListItem{ Text="IMXA-460", Value = "Imxa-460" },
                          new SelectListItem{ Text="VIBXPERT", Value = "VIBXPERT" },
                     new SelectListItem{ Text="CSI-2130", Value = "CSI-2130"},
                      new SelectListItem{ Text="CSI-2140", Value = "CSI-2140" },
                         new SelectListItem{ Text="Kohtect-C911", Value = "Kohtect-C911"},
                     new SelectListItem{ Text="FIELDPAQ", Value = "FIELDPAQ"},
                      new SelectListItem{ Text="VB8", Value = "VB8" },
                         new SelectListItem{ Text="ADASH-4400", Value = "ADASH-4400" },
                     new SelectListItem{ Text="COCO-80", Value = "COCO-80"}
                 }, "Select Instrument", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.InstrumentUsed, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div id="filetype" class="form-group">
                    @Html.RequiredLabelFor(model => model.FileType, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9" id="fileType" style="color:black">
                        @*<input type="radio" name="btnRadio" value="Data" checked="checked" class="radio radio-inline" disabled="disabled" /> Data File
                            <input type="radio" name="btnRadio" value="Image" class="radio radio-inline" disabled="disabled" /> Graph Image*@
                        <input type="radio" name="btnRadio" value="Route" checked="checked" class="radio radio-inline" /> Full Route
                        <input type="radio" name="btnRadio" value="File" class="radio radio-inline" /> Single File
                    </div>
                </div>
                <div class="form-group ">
                    @Html.RequiredLabelFor(model => model.FileName, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        <input type="file" dir="rtl" title="Choose any File or Folder" draggable="true" name="UploadedFile" id="fileToUpload" class="form-control" />
                        <span class="field-validation-error" id="ErrorText" style="color: red"></span>
                    </div>
                </div>

                @*<div class="form-group ">
                        @Html.LabelFor(model => model.NoOfMachines, new { @class = "col-md-3 control-label" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.NoOfMachines, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NoOfMachines, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.NoOfPoints, new { @class = "col-md-3 control-label" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.NoOfPoints, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NoOfPoints, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group ">
                    @Html.LabelFor(model => model.AnalysisMethod, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownList("AnalysisMethod", new List<SelectListItem>{  new SelectListItem{ Text="Indicative Analysis", Value = "Indicative" },  new SelectListItem{ Text="VibAnalyst Analysis", Value = "VibAnalyst",Selected=true}
                 }, new { @class = "form-control", @readonly = "true", disabled = "disabled" })
                        @Html.ValidationMessageFor(m => m.AnalysisMethod, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group ">
                    @Html.LabelFor(model => model.Description, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Description, 5, 25, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div><legend></legend>
                <div class="form-actions">
                    <button type="submit" id="btnSubmit" class="col-md-offset-2 col-md-3 btn btn-sm btn-success text-center">Upload Your Data</button>
                    @Html.ActionLink("Show Previous Data", "GetPreviosData", "Upload", new { area = "RemoteAnalysis" }, new  { @class = "col-md-offset-1 col-md-3 btn btn-sm btn-danger" })
                </div>
            }
        </div>
    </div>
   
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/jscript">
    $("#filetype").hide();
    jQuery.inArray(extension, dfile);
    var rfile = ['rar'];
    var dfile = ['sdf', 'txt', 'dat', 'uff', 'wav', 'txt', 'xls', 'doc', 'docx', 'xlsx', 'csv', 'rar', 'fft'];
    var ifile = ['bmp', 'gif', 'jpeg', 'jpg', 'png', 'pdf'];
    var radiocheck;
    var len;
    var q = 1;
    var d = 0;
    var extension;

    // for checking radio button
    $(document).ready(function checkRadioChecked() {
        $('#filetype').change(function () {
            var radiocheck = $('.radio:checked').val();
            if (radiocheck == "Route") {
                len = rfile.length;
                q = 1;
                $("#fileToUpload").attr("accept", ".rar");
                $("#fileToUpload").val('');
            }
            if (radiocheck == "File") {
                len = dfile.length;
                q = 2;
                $("#fileToUpload").attr("accept", ".xls,.sdf,.txt,.dat,.uff,.wav,.txt,.xls,.doc,.docx,.xlsx,.csv,.fft");
                $("#fileToUpload").val('');
            }
        });
    });
    // for checking instrument used .....
    $(function () {
        $("#Instrument").change(function () {
            var instrumentName = $("#Instrument").val();
            checkInstrument();
        });
    });
    //get file path from client system
    function getNameFromPath(strFilepath) {
        var objRE = new RegExp(/([^\/\\]+)$/);
        var strName = objRE.exec(strFilepath);
        if (strName == null) {
            return null;
        }
        else {
            return strName[0];
        }
    }

    $("#btnSubmit").on("click", function () {
        if ($('#fileToUpload').val() == "") {
            $("#ErrorText").html("Please upload file");
            return false;
        }
        else {
            return checkfile();
        }
    });


    //get file size
    function GetFileSize(fileid) {
        try {
            var fileSize = 0;
            //for IE
            fileSize = $("#" + fileid)[0].files[0].size //size in kb
            fileSize = fileSize / 1048576; //size in mb
            return fileSize;
        }
        catch (e) {
            alert("Error is :" + e);
        }
    }

    $("#btnaddRow").click(function () {
        var rowCount = $("table tr").length;
        var firstRow = $("table tr:Last").clone();
        firstRow.children("td input").each(function () {
            this.id = this.id.replace("_0", "_" + rowCount);
        });
        var newid = this.id + rowCount;
        $("table").append(firstRow);
    });

    //get file path from client system
    function getNameFromPath(strFilepath) {
        var objRE = new RegExp(/([^\/\\]+)$/);
        var strName = objRE.exec(strFilepath);
        if (strName == null) {
            return null;
        }
        else {
            return strName[0];
        }
    }
    // submit file check

    $("#btnSubmit").on("click", function () {
        if ($('#fileToUpload').val() == "") {
            $("#ErrorText").html("Please upload file");
            return false;
        }
        else {
            return checkfile();
        }
    });

    // this will check file extension and file type

    function checkfile() {
        var file = getNameFromPath($("#fileToUpload").val());
        var size = GetFileSize('fileToUpload');
        if (size > 150) {
            alert("You can upload file only up to 150 MB");
            $("#fileToUpload").val('');
            return false;
        }

        else {
            extension = file.substr((file.lastIndexOf('.') + 1));
            if (q == 1) {
                for (var i = 0; i < len; i++) {
                    if (extension == rfile[i]) { d = 1; }
                }
            }
            if (q == 2) {
                for (var j = 0; j < len; j++) {
                    if (extension == dfile[j]) { d = 1; }
                }
            }
            if (d == 0) {
                $("#ErrorText").text("Please check your file extension and Try again !");
                return false;
            }
        }
    }
    function checkInstrument() {
        var value = $('#Instrument').val();
        if (value == "Kohtect-C911") {
            $("#filetype").show();
            q = 1;
            len = rfile.length;
        }
        else {
            $("#filetype").hide();
            len = dfile.length;
        }
    }
    $(function () {
        $("#fileToUpload").change(function () {
            checkfile();
        });
    });

    //////////////////////////////////////////////////////////////

    $(document).ready(function () {
        $("#fileToUpload").attr("accept", ".rar");
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            extension = fileName.substr((fileName.lastIndexOf('.') + 1));

            if (radiocheck == "Route")
                if (jQuery.inArray(extension, rfile) == -1) {
                    alert("please select correct file type !");
                    $("#fileToUpload").val('');
                    $("#ErrorText").html("Please upload compressed route !");
                }
                else
                    $("#ErrorText").html("");
            if (radiocheck == "File")
                if (jQuery.inArray(extension, dfile) == -1) {
                    alert("please select correct file type");
                    $("#fileToUpload").val('');
                    $("#ErrorText").html("Please upload file");
                }
                else
                    $("#ErrorText").html("");
        });
    });

    $("#btnPreviousData").click(function ()
    {

    });
</script>

VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Views/Upload/_DisplayArea.cshtml
@model VibExchange.Areas.RemoteAnalysis.Models.AreaData

@{
    var status = TempData["NodeAvailability"];
}

@using (Html.BeginForm("UpdateArea", "Upload", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <legend class="navbar-left" style="color:lightcoral">Area Information</legend>

    <div>
        <div class="display-none">
            @Html.HiddenFor(model => model.AreaID)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AreaName, new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.AreaName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.AreaName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreaDetail, htmlAttributes: new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-8">
                @Html.TextAreaFor(m => m.AreaDetail, 3, 10, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AreaDetail, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="form-group">
    <div class="col-md-offset-4 col-md-8">
        <button type="button" id="btnUpdateArea" class="btn btn-success">Save Detail</button>
    </div>
</div>

<script>
    $('#btnUpdateArea').click(function () {
        $.ajax({
            url: "@Url.Action("UpdateArea", "Upload", new { area = "RemoteAnalysis" })",
            type: 'POST',
            data: $('form').serialize(),
            success: function (data) {
                $('#graphDisplay').html('');
                $('#graphDisplay').html(data);
                alert("Area details update succesfully.");
            }
        });
    });
</script>

VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Views/Upload/_DisplayGraph1.cshtml
@model com.iAM.chart2dnet.ChartView
@using com.iAM.chart2dnet
@{
    ViewBag.Title = "_DisplayGraph1";
    Layout = "~/Views/Shared/_VibExchangeLayout.cshtml";
}

<h2>_DisplayGraph1</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

   <div id="qchart">
       
   </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    @*$("#qchart").append(@Model.Draw(@Model.)*@
</script>

VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Views/Upload/_DisplayMachine.cshtml
@model VibExchange.Areas.RemoteAnalysis.Models.MachineData

@{
    var status = TempData["NodeAvailability"];
}

@using (Html.BeginForm("UpdateMachine", "Upload", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <legend class="navbar-left" style="color:lightcoral">Machine Information</legend>
    <div>
        <div class="display-none">
            @Html.HiddenFor(model => model.MachineID)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.MachineName, new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.MachineName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.MachineName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MachineClass, htmlAttributes: new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.DropDownList("machineClass", new List<SelectListItem>{
                  new SelectListItem{ Text="Class 1", Value = "Class1" },
                   new SelectListItem{ Text="Class 2", Value = "Class2" },
                     new SelectListItem{ Text="Class 3", Value = "Class3" },
                      new SelectListItem{ Text="Class 4", Value = "Class4" }

                 }, "Select Machine Class", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MachineClass, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.RPMDriven, new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.RPMDriven, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.RPMDriven, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PulseRevolution, new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.PulseRevolution, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PulseRevolution, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MachineDetail, htmlAttributes: new { @class = " col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextAreaFor(m => m.MachineDetail, 3, 10, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MachineDetail, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <button type="button" id="btnUpdateMachine" class="btn btn-success">Save Detail</button>
            </div>
        </div>
    </div>
}

<script>
    $('#btnUpdateMachine').click(function () {
        $.ajax({
            url: "@Url.Action("UpdateMachine", "Upload", new { area = "RemoteAnalysis" })",
            type: 'POST',
            data: $('form').serialize(),
            success: function (data) {
                $('#graphDisplay').html('');
                $('#graphDisplay').html(data);
                alert("Machine details update succesfully.");
            }
        });
    });
</script>

VibExchange 19 Jan 2018/VibExchange/Areas/RemoteAnalysis/Views/Upload/_DisplayTrain.cshtml
@model VibExchange.Areas.RemoteAnalysis.Models.TrainData

@{
    var status = TempData["NodeAvailability"];
}

@using (Html.BeginForm("UpdateTrain", "Upload", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <legend class="navbar-left" style="color:lightcoral">Train Information</legend>

    <div>
        <div class="display-none">
            @Html.HiddenFor(model => model.TrainID)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.TrainName, new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.TrainName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TrainName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NoOfMachine, htmlAttributes: new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.DropDownList("NoOfMachine", new List<SelectListItem>{
               new SelectListItem{ Text="1", Value = "1" },
                     new SelectListItem{ Text="2", Value = "2" },
                      new SelectListItem{ Text="3", Value = "3" },
                       new SelectListItem{ Text="4", Value = "4" },
                        new SelectListItem{ Text="5", Value = "5" },
                         new SelectListItem{ Text="6", Value = "6" },
                          new SelectListItem{ Text="7", Value = "7" },
                           new SelectListItem{ Text="8", Value = "8" },
                         new SelectListItem{ Text="9", Value = "9" },
                          new SelectListItem{ Text="10", Value = "10" },
                           new SelectListItem{ Text="10+", Value = "10+" }

                 }, "Select No of Machine", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NoOfMachine, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TrainDetail, htmlAttributes: new { @class = "col-md-2 col-md-offset-1 control-label" })
            <div class="col-md-8">
                @Html.TextAreaFor(m => m.TrainDetail, 3, 10, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainDetail, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="form-group">
    <div class="col-md-offset-4 col-md-8">
        <button type="button" id="btnUpdateTrain" class="btn btn-success">Save Detail</button>
    </div>
</div>
<script>
    $('#btnUpdateTrain').click(function () {
        $.ajax({
            url: "@Url.Action("UpdateTrain", "Upload", new { area = "RemoteAnalysis" })",
            type: 'POST',
            data: $('form').serialize(),
            success: function (data) {
                $('#graphDisplay').html('');
                $('#graphDisplay').html(data);
                alert("Train details update succesfully.");
            }
        });
    });
</script>