VibExchange 19 Jan 2018/VibExchange/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;
using VibExchange.Filters;
using VibExchange.Models;

namespace VibExchange.Controllers
{
    [InitializeSimpleMembershipAttribute]
    public class ClientsController : Controller
    {
        UploadFile client = new UploadFile();
        private UsersContext db = new UsersContext();
        public ActionResult ClientList()
        {
            var clients = ClientsRecord.GetClients();
            ViewBag.ClientsList = clients;
            return View(clients);
        }

        public ActionResult AllUserList()
        {
            return View();
        }

        public ActionResult getUserData()
        {
            var UserList = ClientsRecord.AllUserList();
            var UserDat = Json(UserList, JsonRequestBehavior.AllowGet);
            return UserDat;
        }

        public ActionResult ShowUserDetail(string UserName)
        {
            UserDetail ud = new UserDetail();
            using (DBClass context = new DBClass())
            {
                context.AddParameter("@UserName",UserName);
              DataTable dtUser = context.getData("getUserData", CommandType.StoredProcedure);
              if (dtUser.Rows.Count > 0)
              {
                  ud.FullName = Convert.ToString(dtUser.Rows[0]["FullName"]);
                  ud.EmailID = Convert.ToString(dtUser.Rows[0]["EmailID"]);
                  ud.Phone = Convert.ToString(dtUser.Rows[0]["Phone"]);
                  ud.Company = Convert.ToString(dtUser.Rows[0]["Company"]);
                  ud.UserRole = Convert.ToString(dtUser.Rows[0]["Role"]);
                  ud.Address = Convert.ToString(dtUser.Rows[0]["Address"]);
                  ud.City = Convert.ToString(dtUser.Rows[0]["City"]);
                  ud.State = Convert.ToString(dtUser.Rows[0]["State"]);
                  ud.Country = Convert.ToString(dtUser.Rows[0]["Country"]);
              }
            }
            return View("_ShowUserDetail", ud);
        }

        public ActionResult Detail(int id)
        {
            UploadFile uploadMachine = new UploadFile();
            using (DBClass context = new DBClass())
            {
                context.AddParameter("@FileID", id);
                DataTable dt = context.getData("getCurrentFileDetailByID", CommandType.StoredProcedure);

                //if (Convert.ToString(dt.Rows[0]["FileType"]) == "Data")
                //{
                //    filetype = true;
                //}
                uploadMachine.FileID = Convert.ToInt32(dt.Rows[0]["ID"]);
                uploadMachine.fileName1 = Convert.ToString(dt.Rows[0]["FileName"]);
                uploadMachine.Instrument = Convert.ToString(dt.Rows[0]["InstrumentUsed"]);
                uploadMachine.AnalysisType = Convert.ToString(dt.Rows[0]["AnalysisType"]);
                uploadMachine.Description = Convert.ToString(dt.Rows[0]["Description"]);
            }
            ViewBag.FileID = uploadMachine.FileID;
            return View(uploadMachine);
            //using (DBClass context = new DBClass())
            //{
            //    DataTable data = context.getData("select * from UploadData where ID = '" + id + "'", CommandType.Text);
            //    if (Request.IsAjaxRequest())
            //    {
            //        upload.fileName1 = Convert.ToString(data.Rows[0]["FileName"]);
            //        upload.Instrument = Convert.ToString(data.Rows[0]["InstrumentUsed"]);
            //        upload.machine1 = upload.GetList(id);
            //        upload.Description = Convert.ToString(data.Rows[0]["Description"]);
            //        upload.AnalysisType = Convert.ToString(data.Rows[0]["AnalysisType"]);
            //        ViewBag.Message = "Your File Detail";
            //        var machineDetail = upload;
            //        ViewBag.MachineDetail = machineDetail;
            //        return PartialView("_FileDetail", upload);
            //    }
            //    else
            //    { return PartialView("_FileDetail", upload); }
            //}
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            UploadFile upload = new UploadFile();
            EditFile client = new EditFile();
            using (DBClass context = new DBClass())
            {
                DataTable data = context.getData("select * from UploadData where ID = '" + id + "'", CommandType.Text);
                //HttpPostedFileBase filename = upload.fileName;
                string fileName = Convert.ToString(data.Rows[0]["FileName"]);
                string fname = Session["UserName"].ToString() + "@" + Convert.ToString(data.Rows[0]["FileName"]);
                var path = Path.Combine(Server.MapPath("~/Files"), fname);
                //if (System.IO.File.Exists(path))
                //{
                //    ModelState.AddModelError("File", "This file is already exist!");
                //}

                var filecontent = GetFileFromDisk(fname);
                string filetype = null;
                if (Request.IsAjaxRequest())
                {
                    filetype = Convert.ToString(data.Rows[0]["FileType"]);
                    if (filetype == "Data")
                    {
                        ViewBag.FileType = "Data";
                        //upload.FileType = ViewBag.FileType;
                    }
                    upload.TotalPoint = Convert.ToInt32(data.Rows[0]["PointCount"]);
                    upload.currentfile = Convert.ToString(data.Rows[0]["FileName"]);
                    upload.Instrument = Convert.ToString(data.Rows[0]["InstrumentUsed"]);
                    upload.AnalysisType = Convert.ToString(data.Rows[0]["AnalysisType"]);
                    upload.Description = Convert.ToString(data.Rows[0]["Description"]);
                    ViewBag.Message = "Edit Your File";
                    return PartialView("_UploadData", upload);

                }
                else
                {
                    filetype = Convert.ToString(data.Rows[0]["FileType"]);
                    if (filetype == "Image")
                    {
                        ViewBag.FileType = "Image";
                        //upload.FileType = ViewBag.FileType;
                    }
                    upload.TotalPoint = Convert.ToInt32(data.Rows[0]["PointCount"]);
                    upload.currentfile = Convert.ToString(data.Rows[0]["FileName"]);
                    upload.Instrument = Convert.ToString(data.Rows[0]["InstrumentUsed"]);
                    upload.AnalysisType = Convert.ToString(data.Rows[0]["AnalysisType"]);
                    upload.Description = Convert.ToString(data.Rows[0]["Description"]);
                    ViewBag.Message = "Edit Your File";
                    return PartialView("_UploadData", upload);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection formcollection)
        {
            UploadFile upload = new UploadFile();
            var file = HttpContext.Request.Files["FiletoChange"];
            string fileName = null; ;
            if (file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
            }
            else
            {
                fileName = formcollection["currentfile"];
            }
            string fname = Session["UserName"].ToString() + "@" + fileName;
            double TotalCost = 0.0;
            var path = Path.Combine(Server.MapPath("~/Files"), fname);
            using (DBClass context = new DBClass())
            {
                var fil = formcollection["fileType"];
                var analysis = formcollection["AnalysisType"];
                string analysisType = null;
                int totalPoint = 0;
                totalPoint = Convert.ToInt32(formcollection["PointCount"]);

                switch (analysis)
                {
                    case "Indicative Analysis":
                        {
                            analysisType = "Indicative Analysis";

                            DataTable dt = context.getData("Select * from AnalysisCost where ServiceType='" + analysisType + "'", CommandType.Text);
                            if (fil == "Data")
                            { TotalCost = Convert.ToDouble(totalPoint) * Convert.ToDouble(dt.Rows[0]["CostPerPoint"]); }
                            else { TotalCost = Convert.ToDouble(dt.Rows[0]["CostPerGraphOrImage"]); }
                            break;

                        }
                    case "VibAnalyst Analysis":
                        {
                            analysisType = "VibAnalyst Analysis";
                            DataTable dt = context.getData("Select * from AnalysisCost where ServiceType='" + analysisType + "'", CommandType.Text);
                            if (fil == "Data")
                            { TotalCost = Convert.ToDouble(totalPoint) * Convert.ToDouble(dt.Rows[0]["CostPerPoint"]); }
                            else
                            { TotalCost = Convert.ToDouble(dt.Rows[0]["CostPerGraphOrImage"]); }
                            break;
                        }
                    case "Expert Analysis":
                        {
                            analysisType = "Expert Analysis";
                            DataTable dt = context.getData("Select * from AnalysisCost where ServiceType='" + analysisType + "'", CommandType.Text);
                            if (fil == "Data")
                            { TotalCost = Convert.ToDouble(totalPoint) * Convert.ToDouble(dt.Rows[0]["CostPerPoint"]); }
                            else
                            { TotalCost = Convert.ToDouble(dt.Rows[0]["CostPerGraphOrImage"]); }

VibExchange 19 Jan 2018/VibExchange/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VibExchange.Models;

namespace VibExchange.Controllers
{
    public class ServicesController : Controller
    {
        //
        // GET: /Services/

        public ActionResult ServiceDetail()
        {
            ViewBag.method = "Manually Analysis Method";
            return View();
        }
        public ActionResult AnalysisMethod(string id)
        {
            ViewBag.AnalysisMethod = id;
            if (Session["UserName"] != null)
            {
                ViewBag.UserName = "";
            }
            else
            {
                ViewBag.UserName = Session["UserName"].ToString();
            }
            return View();
        }

        public ActionResult getService(string serviceID)
        {
            AnalysisMethod file = new AnalysisMethod();
            file.CostList = GetCostList();
            switch (serviceID)
            {
                case "Centrifugal Pump":
                    {
                        return View("CentrifugalpumpService",file);
                    }
                case "Fans":
                    {
                        return View("FansService", file);
                    }
                case "Bearings":
                    {
                        return View("BearingsService", file);
                    }
                case "Gears":
                    {
                        return View("GearsService", file);
                    }
                case "Motor Current":
                    {
                        return View("MotorcurrentService", file);
                    }
                case "HFD":
                    {
                        return View("HFDService", file);
                    }
                default:
                    {
                        return View("ServiceDetail");
                    }
            }

        }

        public List<UploadFile> GetCostList()
        {
            List<UploadFile> allList = new List<UploadFile>();

            using (DBClass context = new DBClass())
            {
                DataTable dt = context.getData("select * from AnalysisCost", CommandType.Text);
                foreach (DataRow dr in dt.Rows)
                {
                    allList.Add(new UploadFile
                    {
                        sr = Convert.ToString(dr["ServiceType"]),
                        costperpoint = Convert.ToString(dr["CostPerPoint"]),
                        costpergraph = Convert.ToString(dr["CostPerGraphOrImage"]),
                        AnalysisTime = Convert.ToString(dr["AnalysisTime"])
                    });
                }
                return allList;
            }
        }
    }
}

VibExchange 19 Jan 2018/VibExchange/Views/UploadDownload/AnalysisMode.cshtml
@model VibExchange.Models.AnalysisMethod

@{
    ViewBag.Title = "AnalysisMode";
    Layout = "~/Views/Shared/_VibExchangeLayout.cshtml";
}

<style>
    .heading {
        color: #4800ff;
        font-family: Calibri;
        font-size: 18px;
    }
</style>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div class="page-text">
            <h4>@ViewBag.AnalysisMethod</h4>
            <div class="row-fluid">
                <p class="para">
                    <span>
                        VibExchange offers offline vibration analysis for your machine.In our Manually Analysis Method we provide feature to upload your
                        machine data and other some inputs about your machine on that you have taken data.
                        Our Manually Analysis Method provide depth vibration analysis on your machinery using our offline advanced vibration analyzer software.
                        Also we provide system generated different different kind of reports.
                    </span>
                </p>
                <p class="heading">
                    <img style="padding-right: 5px;" src="~/Images/marker1.png" />
                    How to analyse your data ?
                </p>
                <p>
                    <span>
                        There are simply few steps process to analyse your data :-
                    </span>
                </p>
                <p>
                    <span>
                        <img style="padding-right: 10px;" src="~/Images/steps.png" />
                        Login with your user name and password.
                    </span>
                </p>
                <p>
                    <span>
                        <img style="padding-right: 10px;" src="~/Images/steps.png" />
                        Select your file to upload.
                    </span>
                </p>
                <p>
                    <span>
                        <img style="padding-right: 10px;" src="~/Images/steps.png" />
                        Select your instrument used in collecting data on machine.
                    </span>
                </p>
                <p>
                    <span>
                        <img style="padding-right: 10px;" src="~/Images/steps.png" />
                        Fill your machine detail table and add new machine if your file contain data of multiple machine.
                    </span>
                </p>
            </div>
            <div class="row-fluid">
                <p class="heading">
                    <img style="padding-right: 5px;" src="~/Images/dollor.png" />
                    Consultation charges of our services :
                </p>
                @Html.Partial("_CostTable", Model.CostList)
            </div>
            <br />
            <div class="row-fluid">
                <a style="margin-left:20px;margin-bottom:20px;color:blue;" id="btnUploadManual" class="btn btn-default" href="@Url.Action("UploadFile", "UploadDownload", new { flag=ViewBag.AnalysisMethod})" onclick="OnDeleteClick(this);"> Upload Your Data &raquo;</a>

            </div>
            <div id="upload">

            </div>
        </div>
    }
    @*<div class="row-fluid">
        @Html.ActionLink("Back to All", "ServiceDetail", "Services")
    </div>*@

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('btnUploadManual').click(OnDeleteClick);
    });
    function OnDeleteClick(e) {
        if (Session["UserName"] == null) {
            // var flag = postMessage('Please login or register before upload your data !');
            var flag = confirm('Please login or register before upload your data !');
            if (flag) {
                $.ajax({
                    url: '/UploadDownload/UploadFile',
                    type: 'POST',
                    data: { id: flag },
                    dataType: 'ActionResult'
                    //success: function (result) { alert(result); $("#" + employeeId).parent().parent().remove(); },
                    //error: function () { alert('Error!'); }
                });
            }
            return false;
        }
        else { return true; }
    }
</script>
<script type="text/javascript">
    @* var message = '@message';
    if (message)
        alert(message);*@

</script>

VibExchange 19 Jan 2018/VibExchange/Views/UploadDownload/UploadFile.cshtml
@model VibExchange.Models.UploadFile
@{
    ViewBag.Title = "File Upload";
    Layout = "~/Views/Shared/_VibExchangeLayout.cshtml";

}
@if (@ViewBag.Message != null)
{
    <div>
        <button type="button">@ViewBag.Message</button>
    </div>
}
    @*@if (TempData["Error"] != null)
        {
            <p>@TempData["Error"]</p>
        }*@

    <script src="~/Scripts/jquery-1.8.3.min.js"></script>
    <script src="~/JQGridReq/jquery-1.9.0.min.js"></script>
    <link href="~/JQGridReq/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
    <script src="~/JQGridReq/jquery.jqGrid.js"></script>
    <script src="~/JQGridReq/grid.locale-en.js"></script>
    <link href="~/JQGridReq/ui.jqgrid.css" rel="stylesheet" />

    <style>
        .text {
            text-align: left;
            font-weight: bold;
            font-size: smaller;
        }
    </style>

    <h4>Please enter your detail. </h4>

    <div class="container row-fluid">

        @using (Html.BeginForm("UploadFile", "UploadDownload",  new { ReturnUrl = this.Request.RawUrl },FormMethod.Post, new { enctype = "multipart/form-data", @class = " form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class=" form-horizontal" role="form">
                <div id="filetype" class="form-group ">
                    @Html.LabelFor(model => model.FileType, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.RadioButtonFor(model => model.FileType, "Data", new { @class = "radio radio-inline", id = "data", })
                        @Html.Label("DataFile", "Data File")
                        @Html.RadioButtonFor(model => model.FileType, "Image", new { @class = "radio radio-inline", id = "image" })
                        @Html.Label("GraphImage", "Graph Image")
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group ">
                    @Html.LabelFor(model => model.fileName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        <input type="file" dir="rtl" draggable="true" name="UploadedFile" id="fileToUpload" class="form-control" multiple="single" />
                        <span class="field-validation-error" id="ErrorText" style="color: red"></span>
                    </div>
                </div>

                <div class="form-group ">
                    @Html.LabelFor(model => model.Instrument, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownList("Instrument", new List<SelectListItem>{
                    new SelectListItem{ Text="IMPAQ-ELITE", Value = "IMPAQ-ELITE" },
                     new SelectListItem{ Text="DI-460", Value = "DI-460"},
                      new SelectListItem{ Text="ENPAC", Value = "NPAQ" },
                       new SelectListItem{ Text="IMXA-460", Value = "Imax-460" },
                          new SelectListItem{ Text="VIBXPERT", Value = "VIBXPERT" },
                     new SelectListItem{ Text="CSI-2130", Value = "CSI-2130"},
                      new SelectListItem{ Text="CSI-2140", Value = "CSI-2140" },
                         new SelectListItem{ Text="C911", Value = "C911" },
                     new SelectListItem{ Text="FIELDPAQ", Value = "FIELDPAQ"},
                      new SelectListItem{ Text="VB8", Value = "VB8" },
                         new SelectListItem{ Text="ADASH-4400", Value = "ADASH-4400" },
                     new SelectListItem{ Text="COCO-80", Value = "COCO-80"}
                 }, "Select Instrument", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Instrument, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group ">
                    @Html.LabelFor(model => model.AnalysisType, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownList("AnalysisType", new List<SelectListItem>{  new SelectListItem{ Text="Indicative Analysis", Value = "Indicative" },  new SelectListItem{ Text="VibAnalyst Analysis", Value = "VibAnalyst"}
                 }, "Select Analysis Type", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.AnalysisType, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group ">
                    @Html.LabelFor(model => model.Description, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, 5, 25, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
            @*
                <div class="col-md-2">
                    @Html.ActionLink("Back to Services", "ServiceDetail", "Services")
                </div>*@
                    <div style="padding-top: 20px; padding-left: 10px; max-width: 1100px;">
            @*<input type="submit" id="btnSubmit" value="Submit your file" class=" btn btn-default" onclick="javascript: return Postsubmit()" />*@
                        <button type="submit" id="btnSubmit" class="btn btn-default" onclick="location.href='@Url.Action("UploadFile", "UploadDownload", new { id = ViewBag.AnalysisMethod })'">Submit your file</button>

                    </div>
                </div>
            </div>
        }
    </div>
    <div id='myModal' class='modal fade in'>
        <div id="mdialog" class="modal-dialog">
            <div class="modal-content">
                <button type="button" style="padding-right: 10px; padding-top: 10px; color: red;" class="close" data-dismiss="modal" aria-hidden="false" onclick="closeModal()">Close</button>
                <div id='myModalContent'></div>
            </div>
        </div>
    </div>
    <div id='myModalDriven' class='modal fade in'>
        <div class="modal-dialog">
            <div class="modal-content">

                <button type="button" style="padding-right: 10px; padding-top: 10px; color: red;" class="close" data-dismiss="modal" aria-hidden="false" onclick="closeModal()">Close</button>
                <div id='myModalContentDriven'></div>
            </div>
        </div>
    </div>
    <div id="divForm">
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }


    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $("a[data-modal]").on("click", function (e) {
                $('#myModalContent').load(this.href, function () {
                    //$('#myModal').toggle();
                    $('#myModal').toggle({
                        backdrop: 'static',
                        keyboard: true
                    }, 'show');
                });
                return false;
            });
        });

        function closeModal() {
            $('#myModal').toggle();
        }

    </script>

    <script type="text/jscript">
        var radiocheck;
        $('.radio').click(function () {
            radiocheck = $('.radio:checked').val();
        });

        //get file size
        function GetFileSize(fileid) {
            try {
                var fileSize = 0;
                //for IE
                fileSize = $("#" + fileid)[0].files[0].size //size in kb
                fileSize = fileSize / 1048576; //size in mb
                return fileSize;
            }
            catch (e) {
                alert("Error is :" + e);
            }
        }
        function deleteRow(row) {
            var rowCount = $('#tblMachineDetail tr').length;
            if (rowCount > 2) {
                var i = row.parentNode.parentNode.rowIndex;
                document.getElementById('tblMachineDetail').deleteRow(i);
            }
            else {
                alert("You can delete.Atleast one machine should be available.")
            }
        }


        function ShowDeatil(row) {
            var rowIndex = row.parentNode.rowIndex;
            if (rowIndex == 1) {
            }
            else if (rowIndex == 2) { }
            else { }
        }

        $("#btnaddRow").click(function () {
            var rowCount = $("table tr").length;
            var firstRow = $("table tr:Last").clone();
            firstRow.children("td input").each(function () {
                this.id = this.id.replace("_0", "_" + rowCount);
            });
            var newid = this.id + rowCount;
            $("table").append(firstRow);
            alert(newid);
        });

        //get file path from client system
        function getNameFromPath(strFilepath) {
            var objRE = new RegExp(/([^\/\\]+)$/);
            var strName = objRE.exec(strFilepath);
            if (strName == null) {
                return null;
            }
            else {
                return strName[0];
            }
        }

        $("#btnSubmit").on("click", function () {
            if ($('#fileToUpload').val() == "") {
                $("#ErrorText").html("Please upload file");

                return false;
            }
            else {
                return checkfile();
            }
        });

        function checkfile() {
            var file = getNameFromPath($("#fileToUpload").val());
            if (file != null) {
                var extension = file.substr((file.lastIndexOf('.') + 1));
                // alert(extension);
                flag = true;
            }
            if (flag == false) {
                $("#ErrorText").text("Please check you file extension and Try again !");
                return false;
            }
            else {
                var size = GetFileSize('fileToUpload');
                if (size > 150) {
                    $("#ErrorText").text("You can upload file up to 150 MB");
                    return false;
                }
                else {
                    return true;
                }
            }
        }
        $(function () {
            $("#fileToUpload").change(function () {
                checkfile();
            });
        });
    </script>